FROM ruby:3.3

ENV LANG C.UTF-8
ENV TZ Asia/Tokyo
ENV RAILS_ENV=development

RUN apt-get update -qq && apt-get install -y \
    ca-certificates curl gnupg postgresql-client vim nano git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

COPY . .

CMD ["bin/dev"]